### ISSUE TITLE
Regular weight is a different design

### ISSUE THREAD

**Issue by yanone** [danhhong/KohSantepheap#2]
The Regular weight of Koh Santepheap is a completely different design. Please replace this with the correct design.
<img width="824" alt="Bildschirmfoto 2021-04-15 um 13 55 12" src="https://user-images.githubusercontent.com/175386/114865638-d704e200-9df2-11eb-8417-cdec6838c13f.png">

**Comment by danhhong** [comment]
OK, I have done
